// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fhkoeln.edb.nftool;

import fhkoeln.edb.nftool.ExerciseDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExerciseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExerciseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExerciseIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ExerciseIntegrationTest: @Transactional;
    
    @Autowired
    private ExerciseDataOnDemand ExerciseIntegrationTest.dod;
    
    @Test
    public void ExerciseIntegrationTest.testCountExercises() {
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", dod.getRandomExercise());
        long count = fhkoeln.edb.nftool.Exercise.countExercises();
        org.junit.Assert.assertTrue("Counter for 'Exercise' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExerciseIntegrationTest.testFindExercise() {
        fhkoeln.edb.nftool.Exercise obj = dod.getRandomExercise();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.Exercise.findExercise(id);
        org.junit.Assert.assertNotNull("Find method for 'Exercise' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Exercise' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExerciseIntegrationTest.testFindAllExercises() {
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", dod.getRandomExercise());
        long count = fhkoeln.edb.nftool.Exercise.countExercises();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Exercise', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fhkoeln.edb.nftool.Exercise> result = fhkoeln.edb.nftool.Exercise.findAllExercises();
        org.junit.Assert.assertNotNull("Find all method for 'Exercise' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Exercise' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExerciseIntegrationTest.testFindExerciseEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", dod.getRandomExercise());
        long count = fhkoeln.edb.nftool.Exercise.countExercises();
        if (count > 20) count = 20;
        java.util.List<fhkoeln.edb.nftool.Exercise> result = fhkoeln.edb.nftool.Exercise.findExerciseEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Exercise' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Exercise' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExerciseIntegrationTest.testFlush() {
        fhkoeln.edb.nftool.Exercise obj = dod.getRandomExercise();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.Exercise.findExercise(id);
        org.junit.Assert.assertNotNull("Find method for 'Exercise' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExercise(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Exercise' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExerciseIntegrationTest.testMerge() {
        fhkoeln.edb.nftool.Exercise obj = dod.getRandomExercise();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.Exercise.findExercise(id);
        boolean modified =  dod.modifyExercise(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fhkoeln.edb.nftool.Exercise merged = (fhkoeln.edb.nftool.Exercise) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Exercise' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExerciseIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", dod.getRandomExercise());
        fhkoeln.edb.nftool.Exercise obj = dod.getNewTransientExercise(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Exercise' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Exercise' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExerciseIntegrationTest.testRemove() {
        fhkoeln.edb.nftool.Exercise obj = dod.getRandomExercise();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Exercise' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.Exercise.findExercise(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Exercise' with identifier '" + id + "'", fhkoeln.edb.nftool.Exercise.findExercise(id));
    }
    
}
