// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fhkoeln.edb.nftool;

import fhkoeln.edb.nftool.TableRowDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TableRowIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TableRowIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TableRowIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TableRowIntegrationTest: @Transactional;
    
    @Autowired
    private TableRowDataOnDemand TableRowIntegrationTest.dod;
    
    @Test
    public void TableRowIntegrationTest.testCountTableRows() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", dod.getRandomTableRow());
        long count = fhkoeln.edb.nftool.TableRow.countTableRows();
        org.junit.Assert.assertTrue("Counter for 'TableRow' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TableRowIntegrationTest.testFindTableRow() {
        fhkoeln.edb.nftool.TableRow obj = dod.getRandomTableRow();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableRow.findTableRow(id);
        org.junit.Assert.assertNotNull("Find method for 'TableRow' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'TableRow' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TableRowIntegrationTest.testFindAllTableRows() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", dod.getRandomTableRow());
        long count = fhkoeln.edb.nftool.TableRow.countTableRows();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'TableRow', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fhkoeln.edb.nftool.TableRow> result = fhkoeln.edb.nftool.TableRow.findAllTableRows();
        org.junit.Assert.assertNotNull("Find all method for 'TableRow' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'TableRow' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TableRowIntegrationTest.testFindTableRowEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", dod.getRandomTableRow());
        long count = fhkoeln.edb.nftool.TableRow.countTableRows();
        if (count > 20) count = 20;
        java.util.List<fhkoeln.edb.nftool.TableRow> result = fhkoeln.edb.nftool.TableRow.findTableRowEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'TableRow' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'TableRow' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TableRowIntegrationTest.testFlush() {
        fhkoeln.edb.nftool.TableRow obj = dod.getRandomTableRow();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableRow.findTableRow(id);
        org.junit.Assert.assertNotNull("Find method for 'TableRow' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTableRow(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'TableRow' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TableRowIntegrationTest.testMerge() {
        fhkoeln.edb.nftool.TableRow obj = dod.getRandomTableRow();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableRow.findTableRow(id);
        boolean modified =  dod.modifyTableRow(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fhkoeln.edb.nftool.TableRow merged = (fhkoeln.edb.nftool.TableRow) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'TableRow' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TableRowIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", dod.getRandomTableRow());
        fhkoeln.edb.nftool.TableRow obj = dod.getNewTransientTableRow(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'TableRow' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'TableRow' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TableRowIntegrationTest.testRemove() {
        fhkoeln.edb.nftool.TableRow obj = dod.getRandomTableRow();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableRow' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableRow.findTableRow(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'TableRow' with identifier '" + id + "'", fhkoeln.edb.nftool.TableRow.findTableRow(id));
    }
    
}
