// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fhkoeln.edb.nftool;

import fhkoeln.edb.nftool.TableColumnDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TableColumnIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TableColumnIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TableColumnIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TableColumnIntegrationTest: @Transactional;
    
    @Autowired
    private TableColumnDataOnDemand TableColumnIntegrationTest.dod;
    
    @Test
    public void TableColumnIntegrationTest.testCountTableColumns() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", dod.getRandomTableColumn());
        long count = fhkoeln.edb.nftool.TableColumn.countTableColumns();
        org.junit.Assert.assertTrue("Counter for 'TableColumn' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TableColumnIntegrationTest.testFindTableColumn() {
        fhkoeln.edb.nftool.TableColumn obj = dod.getRandomTableColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableColumn.findTableColumn(id);
        org.junit.Assert.assertNotNull("Find method for 'TableColumn' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'TableColumn' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TableColumnIntegrationTest.testFindAllTableColumns() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", dod.getRandomTableColumn());
        long count = fhkoeln.edb.nftool.TableColumn.countTableColumns();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'TableColumn', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fhkoeln.edb.nftool.TableColumn> result = fhkoeln.edb.nftool.TableColumn.findAllTableColumns();
        org.junit.Assert.assertNotNull("Find all method for 'TableColumn' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'TableColumn' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TableColumnIntegrationTest.testFindTableColumnEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", dod.getRandomTableColumn());
        long count = fhkoeln.edb.nftool.TableColumn.countTableColumns();
        if (count > 20) count = 20;
        java.util.List<fhkoeln.edb.nftool.TableColumn> result = fhkoeln.edb.nftool.TableColumn.findTableColumnEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'TableColumn' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'TableColumn' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TableColumnIntegrationTest.testFlush() {
        fhkoeln.edb.nftool.TableColumn obj = dod.getRandomTableColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableColumn.findTableColumn(id);
        org.junit.Assert.assertNotNull("Find method for 'TableColumn' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTableColumn(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'TableColumn' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TableColumnIntegrationTest.testMerge() {
        fhkoeln.edb.nftool.TableColumn obj = dod.getRandomTableColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableColumn.findTableColumn(id);
        boolean modified =  dod.modifyTableColumn(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fhkoeln.edb.nftool.TableColumn merged = (fhkoeln.edb.nftool.TableColumn) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'TableColumn' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TableColumnIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", dod.getRandomTableColumn());
        fhkoeln.edb.nftool.TableColumn obj = dod.getNewTransientTableColumn(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'TableColumn' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'TableColumn' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TableColumnIntegrationTest.testRemove() {
        fhkoeln.edb.nftool.TableColumn obj = dod.getRandomTableColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TableColumn' failed to provide an identifier", id);
        obj = fhkoeln.edb.nftool.TableColumn.findTableColumn(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'TableColumn' with identifier '" + id + "'", fhkoeln.edb.nftool.TableColumn.findTableColumn(id));
    }
    
}
