// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fhkoeln.edb.nftool;

import fhkoeln.edb.nftool.Task;
import java.util.Set;

privileged aspect Exercise_Roo_JavaBean {
    
    public Set<Task> Exercise.getTasks() {
        return this.tasks;
    }
    
    public void Exercise.setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }
    
}
