// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fhkoeln.edb.nftool;

import java.io.Serializable;

privileged aspect NewExercise_Roo_Serializable {
    
    declare parents: NewExercise implements Serializable;
    
    private static final long NewExercise.serialVersionUID = 1L;
    
}
