// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fhkoeln.edb.nftool;

privileged aspect TableColumn_Roo_Serializable {
    
    private static final long TableColumn.serialVersionUID = 1L;
    
}
